#!/usr/bin/env python3

from utils import *

with TemporaryDirectory() as tmp, \
    Memo() as memo_1, Memo() as memo_2:
  memo_1.run(['user', 'create',  'user'])
  memo_1.run([
    'silo', 'create', 'filesystem', 'storage',
    '--path', tmp.dir,
  ])
  network_name = memo_1.run([
    'network', 'create', 'network',
    '--silo', 'storage',
    '--kelips', '--k', '1',
    '--as', 'user',
  ])
  network = memo_1.run_json([
    'network', 'export', 'network',
    '--as', 'user',
  ])
  # Device 2
  memo_2.run(['user', 'create', 'user2'])
  memo_2.run([
    'silo', 'create', 'filesystem', 'storage',
    '--path', tmp.dir,
  ])
  memo_2.run(['network', 'import'], input = network)
  user2 = memo_2.run_json  ([
    'user', 'export',  'user2'
  ])
  memo_1.run(['user', 'import'], input = user2)
  passport = memo_1.run_json(['passport', 'create',
      '--user', 'user2', '--network', 'network', '--as', 'user',
      '--deny-write', '--deny-storage',
      '--output', '-'
  ])
  memo_2.run(['passport', 'import'], input = passport)
  try:
    memo_2.run(['network', 'link', 'user/network',
        '--silo', 'storage', '--as', 'user2'])
  except:
    pass
  else:
    raise Exception('link with storage should have failed')
  memo_2.run(['network', 'link', 'user/network',
        '--as', 'user2'])
